### ISSUE TITLE
No parameter for isBookmarked

### ISSUE THREAD

**Issue by joshdaquino** [hitherejoe/GithubTrending#6]
Project Entity has an "isBookmark" param in it's constructor
https://github.com/hitherejoe/GithubTrending/blob/fd79a5783f2a952fe7e40c70752ce08d4061caee/Data/src/main/java/co/joebirch/data/model/ProjectEntity.kt#L3-L6

The mapFromModel doesn't have it
https://github.com/hitherejoe/GithubTrending/blob/fd79a5783f2a952fe7e40c70752ce08d4061caee/Remote/src/main/java/co/joebirch/remote/mapper/ProjectsResponseModelMapper.kt#L10-L12

**Comment by rohitkaradkar** [comment]
I guess `isBookmarked` is only local cache field. 
As remote data source doesn't provide that, it is not present in mapper.

**Comment by hitherejoe** [comment]
@karadkar is correct, there is no bookmarked status that comes from the remote object :)
